#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("niceLabels() works", {

  expect_error(niceLabels())
})

test_that("drawBoxplot() works", {

  expect_error(drawBoxplot())
})

test_that("getPlotCharacterConstants() works", {

  kwb.plot:::getPlotCharacterConstants()
})

test_that("addGridIfTrue() works", {

  expect_error(kwb.plot:::addGridIfTrue())
})

test_that("addLabels() works", {

  expect_error(addLabels())
})

test_that("labelPositionY() works", {

  expect_error(kwb.plot:::labelPositionY())
})

test_that("alternatingPositions() works", {

  kwb.plot:::alternatingPositions()
})

test_that("addTimeAxis() works", {

  expect_error(addTimeAxis())
})

test_that("bestRowColumnSetting() works", {

  expect_error(bestRowColumnSetting())
})

test_that("setMargins() works", {

  setMargins()
})

