#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("arrange_in_png() works", {

  expect_error(arrange_in_png())
})

test_that("output_to_png() works", {

  expect_error(output_to_png())
})

