#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("example_plot() works", {
  skip_on_appveyor()
  example_plot()
})

test_that("example_plot_2() works", {
  skip_on_appveyor()
  example_plot_2()
})

