skip_on_appveyor()
#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("arrange_in_pdf() works", {

  expect_error(arrange_in_pdf())
})

test_that("plot_all_to_pdf() works", {

  expect_error(plot_all_to_pdf())
})

