#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("inchesToUserWidthAndHeight() works", {

  expect_error(kwb.plot:::inchesToUserWidthAndHeight())
})

test_that("cmToUserWidthAndHeight() works", {

  expect_error(cmToUserWidthAndHeight())
})

test_that("userWidthAndHeightToCm() works", {

  expect_error(kwb.plot:::userWidthAndHeightToCm())
})

