#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("mybarplot() works", {

  expect_error(mybarplot())
})

test_that("args_mybarplot() works", {

  kwb.plot:::args_mybarplot()
})

test_that("args_text() works", {

  args_text()
})

test_that("args_yaxis() works", {

  args_yaxis()
})

