#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getPlotRegionRatio() works", {

  kwb.plot:::getPlotRegionRatio()
})

test_that("getPlotRegionSizeInUserCoords() works", {

  getPlotRegionSizeInUserCoords()
})

test_that("getPlotRegionSizeInPixels() works", {

  getPlotRegionSizeInPixels()
})

test_that("getPlotRegionSizeInInches() works", {

  getPlotRegionSizeInInches()
})

test_that("getPlotRegionSizeInCm() works", {

  getPlotRegionSizeInCm()
})

