#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plot_curve_areas_gg() works", {
  skip_on_appveyor()
  expect_error(plot_curve_areas_gg())
})

test_that("plot_curve_area() works", {
  skip_on_appveyor()
  expect_error(plot_curve_area())
})

