#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("stackplot() works", {
  skip_on_appveyor()
  expect_error(stackplot())
})

test_that("stackplotLayout() works", {
  skip_on_appveyor()
  expect_error(kwb.plot:::stackplotLayout())
})

