#
# *** This file was generated by toRoxygen.R.
# *** DO NOT EDIT!
#

# inchesToUserWidthAndHeight ---------------------------------------------------

#' inchesToUserWidthAndHeight
#' 
#' inchesToUserWidthAndHeight
#' 
inchesToUserWidthAndHeight <- function # inchesToUserWidthAndHeight
### inchesToUserWidthAndHeight
(
  inches
)
{
  sizeInches <- getPlotRegionSizeInInches()
  sizeUserCoords <- getPlotRegionSizeInUserCoords()
  list(width  = inches * sizeUserCoords$width / sizeInches$width,
       height = inches * sizeUserCoords$height / sizeInches$height) 
}

# cmToUserWidthAndHeight -------------------------------------------------------

#' cmToUserWidthAndHeight
#' 
#' cmToUserWidthAndHeight
#' 
cmToUserWidthAndHeight <- function # cmToUserWidthAndHeight
### cmToUserWidthAndHeight
(
  cm
)
{
  inches.per.cm <- 1/2.54
  inchesToUserWidthAndHeight(cm * inches.per.cm)
}

# userWidthAndHeightToCm -------------------------------------------------------

#' userWidthAndHeightToCm
#' 
#' userWidthAndHeightToCm
#' 
userWidthAndHeightToCm <- function # userWidthAndHeightToCm
### userWidthAndHeightToCm
(
  width.user, height.user
)
{
  size.cm <- getPlotRegionSizeInCm()
  size.user <- getPlotRegionSizeInUserCoords()
  list(width = width.user * size.cm$width/size.user$width,
       height = height.user * size.cm$height/size.user$height)
}
