#
# *** This file was generated by toRoxygen.R.
# *** DO NOT EDIT!
#

# arrange_in_pdf ---------------------------------------------------------------

#' Arrange Plots in PDF file (DIN A4)
#' 
#' Arrange ggplot objects with gridExtra::grid.arrange and write the result
#'   to a PDF file in DIN A4 format
#' 
#' @param plots list of ggplot objects
#' @param landscape passed to \code{\link[kwb.utils]{preparePdf}}
#' @param \dots arguments passed to \code{\link[gridExtra]{grid.arrange}}
#' 
arrange_in_pdf <- function # Arrange Plots in PDF file (DIN A4)
### Arrange ggplot objects with gridExtra::grid.arrange and write the result
### to a PDF file in DIN A4 format
(
  plots, 
  ### list of ggplot objects
  landscape = TRUE, 
  ### passed to \code{\link[kwb.utils]{preparePdf}}
  ...
  ### arguments passed to \code{\link[gridExtra]{grid.arrange}}
)
{
  pdf_file <- kwb.utils::preparePdf(landscape = landscape)
  do.call(gridExtra::grid.arrange, c(plots, list(...)))
  kwb.utils::finishAndShowPdf(pdf_file)
}

# plot_all_to_pdf --------------------------------------------------------------

#' Print all ggplot Objects to a PDF file
#' 
#' Print all ggplot objects to a PDF file
#' 
#' @param plots list of ggplot objects
#' @param landscape passed to \code{\link[kwb.utils]{preparePdf}}
#' @param \dots further arguments passed to \code{\link[kwb.utils]{preparePdf}}
#' 
plot_all_to_pdf <- function # Print all ggplot Objects to a PDF file
### Print all ggplot objects to a PDF file
(
  plots, 
  ### list of ggplot objects
  landscape = TRUE,
  ### passed to \code{\link[kwb.utils]{preparePdf}}
  ...
  ### further arguments passed to \code{\link[kwb.utils]{preparePdf}}
)
{
  pdf_file <- kwb.utils::preparePdf(landscape = landscape, ...)
  print(plots)
  kwb.utils::finishAndShowPdf(pdf_file)
}
