#
# *** This file was generated by toRoxygen.R.
# *** DO NOT EDIT!
#

# getPlotRegionRatio -----------------------------------------------------------

#' Current plot region's ratio 
#' 
#' Current plot region's height/width ratio 
#' 
#' @return numeric of length one representing the width/height ratio of the current
#'   plot region
#' 
getPlotRegionRatio <- function # Current plot region's ratio 
### Current plot region's height/width ratio 
(
) 
{
  region <- getPlotRegionSizeInCm()
  
  with(region, height / width)
  ### numeric of length one representing the width/height ratio of the current
  ### plot region
}

# getPlotRegionSizeInUserCoords ------------------------------------------------

#' getPlotRegionSizeInUserCoords
#' 
#' getPlotRegionSizeInUserCoords
#' 
#' @return list with elements \emph{width}, \emph{height}, \emph{left}, \emph{bottom}, 
#'   \emph{right}, \emph{top}
#' 
getPlotRegionSizeInUserCoords <- function # getPlotRegionSizeInUserCoords
### getPlotRegionSizeInUserCoords
(
) 
{
  usr <- graphics::par()$usr
  list(width = diff(usr[1:2]), 
       height = diff(usr[3:4]),
       left = usr[1], 
       bottom = usr[3], 
       right = usr[2], 
       top = usr[4])
  ### list with elements \emph{width}, \emph{height}, \emph{left}, \emph{bottom}, 
  ### \emph{right}, \emph{top}
}

# getPlotRegionSizeInPixels ----------------------------------------------------

#' getPlotRegionSizeInPixels
#' 
#' getPlotRegionSizeInPixels
#' 
getPlotRegionSizeInPixels <- function # getPlotRegionSizeInPixels
### getPlotRegionSizeInPixels
(
) 
{  
  dpi <- grDevices::dev.size(units = "px") / grDevices::dev.size(units = "in")
  size.inches <- getPlotRegionSizeInInches()
  list(width = round(size.inches$width * dpi[1]),
       height = round(size.inches$height * dpi[2]))
}

# getPlotRegionSizeInInches ----------------------------------------------------

#' getPlotRegionSizeInInches
#' 
#' getPlotRegionSizeInInches
#' 
getPlotRegionSizeInInches <- function # getPlotRegionSizeInInches
### getPlotRegionSizeInInches
(
) 
{
  mai <- graphics::par()$mai
  
  size <- grDevices::dev.size(units = "in")
  
  list(width  = size[1] - mai[2] - mai[4], height = size[2] - mai[1] - mai[3])
}

# getPlotRegionSizeInCm --------------------------------------------------------

#' getPlotRegionSizeInCm
#' 
#' getPlotRegionSizeInCm
#' 
getPlotRegionSizeInCm <- function # getPlotRegionSizeInCm
### getPlotRegionSizeInCm
(
) 
{
  size.inches <- getPlotRegionSizeInInches()
  cm.per.inch <- 2.54
  list(width = size.inches$width * cm.per.inch,
       height = size.inches$height * cm.per.inch)
}
